version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.6
  win: circleci/windows@2.1.0
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - restore_cache: 
          keys:
            - v2-pkg-cache-{{ checksum "go.sum" }}
      - run: 
          name: test
          command: |
            make test
            bash <(curl -s https://codecov.io/bash)
      - run: env VERSION_STRING=$CIRCLE_TAG make -j 3 build-all
      - run: env VERSION_STRING=$CIRCLE_TAG make latest
      - persist_to_workspace:
          root: .
          paths:
            - bin
      - save_cache:
          key: v2-pkg-cache-{{ checksum "go.sum" }}
          paths:
            - ~/.cache/go-build
            - /go/pkg
      - store_artifacts:
          path: bin
          destination: binaries
      - store_artifacts:
          path: coverage.txt
          destination: coverage.txt
  integration:
    environment: 
      OKTETO_USER: cindylopez
    docker:
      - image: okteto/desk:latest
    steps:
      - checkout
      - restore_cache: 
          keys:
            - v2-pkg-cache-{{ checksum "go.sum" }}
      - attach_workspace:
          at: ./artifacts
      - run:
          name: prepare env
          command: |
            mkdir -p $HOME/.okteto
            touch $HOME/.okteto/.noanalytics
            echo $HOME
            curl -L "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl" -o /usr/local/bin/kubectl
            chmod +x /usr/local/bin/kubectl
            cp $(pwd)/artifacts/bin/okteto-Linux-x86_64 /usr/local/bin/okteto
      - run: 
          name: integration tests (serverside)
          command: |
            unset OKTETO_CLIENTSIDE_TRANSLATION
            make integration
      - run: 
          name: integration tests (clientside)
          command: |
            export OKTETO_CLIENTSIDE_TRANSLATION=true
            make integration
      - save_cache:
          key: v2-pkg-cache-{{ checksum "go.sum" }}
          paths:
            - ~/.cache/go-build
            - /go/pkg
      - store_artifacts:
          path: /root/.okteto
          
  mock-publish-github-release:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - attach_workspace:
          at: ./artifacts
      - deploy:
          name: "Update brew formula"
          command: |
            sha=$(cat ./artifacts/bin/okteto-Darwin-x86_64.sha256 | awk '{print $1}')
            bash ./update_homebrew_formula.sh 0.0.1 $GITHUB_TOKEN $sha 1
  windows-unit:
    executor: win/default
    steps: 
      - checkout
      - restore_cache: 
          keys:
            - v4-pkg-cache-windows-{{ checksum "go.sum" }}
      - run: 
          name: upgrade golang
          command: choco upgrade golang
      - run: 
          name: test
          command: |
            go version
            go test ./...
      - save_cache:
          key: v4-pkg-cache-windows-{{ checksum "go.sum" }}
          paths:
            - C:\Users\circleci\AppData\Local\go-build
            - C:\Users\circleci\go\pkg
            - C:\Go\pkg
      
  release:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - attach_workspace:
          at: ./artifacts
      - aws-s3/sync:
          from: ./artifacts/bin
          to: "s3://downloads.okteto.com/cli"
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
          arguments: |
            --acl public-read \
            --metadata version=${CIRCLE_TAG} \
            --cache-control "max-age=86400" \
            --exclude "*.*.*/" \
      - aws-s3/sync:
          from: ./artifacts/bin
          to: "s3://downloads.okteto.com/cli/${CIRCLE_TAG}"
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
          arguments: |
            --acl public-read \
            --metadata version=${CIRCLE_TAG} \
            --cache-control "max-age=86400" \
          overwrite: false
      - aws-s3/copy:
          from: "./artifacts/bin/okteto-Darwin-x86_64"
          to: "s3://downloads.okteto.com/cloud/cli/okteto-Darwin-x86_64"
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
          arguments: |
            --acl public-read \
            --metadata version=${CIRCLE_TAG} \
            --cache-control "max-age=86400"
      - aws-s3/copy:
          from: "./artifacts/bin/okteto-Darwin-x86_64"
          to: "s3://downloads.okteto.com/cli/okteto-darwin-amd64"
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
          arguments: |
            --acl public-read \
            --metadata version=${CIRCLE_TAG} \
            --cache-control "max-age=86400"
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get -u github.com/tcnksm/ghr
            ghr -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -token $GITHUB_TOKEN -replace $CIRCLE_TAG  ./artifacts/bin/
      - deploy:
          name: "Update brew formula"
          command: |
            sha=$(cat ./artifacts/bin/okteto-Darwin-x86_64.sha256 | awk '{print $1}')
            bash ./update_homebrew_formula.sh $CIRCLE_TAG $GITHUB_TOKEN $sha 0
  release-master:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - attach_workspace:
          at: ./artifacts
      - aws-s3/sync:
          from: ./artifacts/bin
          to: "s3://downloads.okteto.com/cli/master"
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
          arguments: |
            --acl public-read \
            --metadata version=${CIRCLE_SHA1}
workflows:
  version: 2
  build-release:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - integration:
          requires:
            - build
          filters:
            branches:
              only: 
                - master
                - /.*(e2e)/
      - release-master:
          requires:
            - integration
          filters:
            branches:
              only: master
      - mock-publish-github-release:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - build
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
      - windows-unit:
          filters:
            branches:
              only: 
                - master
                - /.*(windows)/