version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest
        environment:
          DEBUG: true

    working_directory: /go/src/github.com/okteto/cnd

    environment:
        BINARY_NAME: "cnd"

    steps:
      - checkout
      - run: go test -v ./...
      - run: go fmt ./...
      - run: go vet ./...
      - run: make

      - persist_to_workspace:
          root: .
          paths:
            - bin

      - store_artifacts:
          path: bin
          destination: binaries
  
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./binaries
      - run:
          name: "Publish Release on GitHub"
          command: |
            ls -la binaries
            VERSION=$(binaries/cnd --version)
            ghr -u okteto -r cnd -c ${CIRCLE_SHA1} -token ${GITHUB_TOKEN} -replace $VERSION  ./binaries/
workflows:
  version: 2
  build-release:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - publish-github-release:
          requires:
            - build
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
      
