name: Lint

on: [pull_request]

jobs:
  merge-conflict:
    name: Merge Conflict
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check merge conflict
        run: grep "^<<<<<<< HEAD" $(git ls-files | xargs) && exit 1 || true
  misspell:
    name: Check Spelling
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Install
        run: wget -O - -q https://git.io/misspell | sh -s -- -b .
      - name: Misspell
        run: git ls-files --empty-directory | xargs ./misspell -error
  trailing-whitespace:
    name: Trailing Whitespace
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check for trailing whitespace
        run: "! git grep -EIn $'[ \t]+$' | grep -v '\\- '"
  superlinter:
    name: superlinter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: github/super-linter@v3
        env:
          ERROR_ON_MISSING_EXEC_BIT: true
          VALIDATE_BASH: true
          VALIDATE_BASH_EXEC: true
          VALIDATE_MARKDOWN: true
          VALIDATE_SHELL_SHFMT: true
          VALIDATE_YAML: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
